name: push

on:
  push:
    branches:
      - dev

jobs:
  sponsor_job:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Generate sponsors section
      uses: JamesIves/github-sponsors-readme-action@1fb9ea792bba91e6c450e4aaefe951c245b789ed # v1.3.1
      with:
        token: ${{ secrets.SPONSORS_TOKEN }}
        file: 'README.md'

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@5c6e9e9f3672ce8fd37b9856193d2a537941e66c # v4.6.0
      with:
        branch: dev
        folder: '.'
        token: ${{ secrets.GITHUB_TOKEN }}
        git-config-name: OpenIddict Bot
        git-config-email: 32257313+openiddict-bot@users.noreply.github.com
        commit-message: Update the sponsors section
